# Generated by Django 2.1.2 on 2018-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20181107_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast_meal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner_meal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch_meal',
            field=models.BooleanField(default=True),
        ),
    ]
