# Generated by Django 2.1.2 on 2018-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0004_auto_20181107_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='breakfast_meal',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner_meal',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch_meal',
            field=models.IntegerField(default=True),
        ),
    ]
