# Generated by Django 2.1.2 on 2018-11-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0005_auto_20181114_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='username1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='breakfast_meal',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner_meal',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch_meal',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
