# Generated by Django 2.1.2 on 2018-11-15 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTwo', '0008_auto_20181114_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='username1',
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
