# Generated by Django 2.1.2 on 2018-11-15 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppTwo', '0010_remove_meal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_meal', models.PositiveIntegerField(default=True)),
                ('lunch_meal', models.PositiveIntegerField(default=True)),
                ('dinner_meal', models.PositiveIntegerField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
