# Generated by Django 2.1.2 on 2018-11-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0014_auto_20181114_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('breakfast_meal', models.PositiveIntegerField(default=True)),
                ('lunch_meal', models.PositiveIntegerField(default=True)),
                ('dinner_meal', models.PositiveIntegerField(default=True)),
            ],
        ),
    ]
